### ISSUE TITLE
the GPP logo is not visible 

### ISSUE THREAD

**Issue by tm-miha** [LedgerProject/home#4]
@antoniodibattista can you please take a look?
[https://ledgerproject.github.io/home/#/teams/GlobalPassportProject](https://ledgerproject.github.io/home/#/teams/GlobalPassportProject)

**Comment by antoniodibattista** [comment]
Hi Miha, yes I’m updating some information, I’ll send you an update in the next hours.

**Comment by tm-miha** [comment]
done
